spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gaj
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  web:
    resources:
      static-locations: classpath:/static/,file:frontend/dist/
security:
  jwt:
    expiration-minutes: 43200
    secret-key: dGhpcyBpcyBteSBzZWN1cmUga2V5IGFuZCB5b3UgY2Fubm90IGhhY2sgaXQ=
server:
  port: 8001

logging:
  level:
    org:
      springframework:
        web: DEBUG
  file:
    name: spring.log

