spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gaj
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_ADDRESS}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
          connectiontimeout: 1000
          timeout: 1000
          writetimeout: 1000
security:
  jwt:
    expiration-minutes: 60
    secret-key: ${SECRET_KEY}

