server:
  port: 8001
security:
  jwt:
    secret-key: dGhpcyBpcyBteSBzZWN1cmUga2V5IGFuZCB5b3UgY2Fubm90IGhhY2sgaXQ=
logging:
  level:
    org:
      springframework:
        web: DEBUG
  file:
    name: spring.log
spring:
  profiles:
    active: dev
