spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gaj
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: to.ada.boczar@gmail.com
    password: vanmjygnojyvvxzj
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
          connectiontimeout: 1000
          timeout: 1000
          writetimeout: 1000
security:
  jwt:
    expiration-minutes: 43200
    secret-key: dGhpcyBpcyBteSBzZWN1cmUga2V5IGFuZCB5b3UgY2Fubm90IGhhY2sgaXQ=

